#lang racket
(define dx 0.000001)
(define (repeated fn n)
  (lambda (x)
          (define (iter k n result)
            (cond ((= k n) result)
                  (else (iter (+ k 1) n (fn result)))))
          (iter 0 n x)))
(define (cube x)
  (* x x x))
(define (smooth f)
  (lambda (x)
          (/ (+ (f (- x dx)) (f x) (f (+ x dx))) 3)))

(define (repeated-smooth n)
  (repeated smooth n))
(newline)
((smooth cube) 10)
(newline)
(((repeated-smooth 10) cube) 10)
